apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-component
  description: The place to be, for great artists
spec:
  type: service
  lifecycle: experimental
  owner: arquitectura-empresarial-team
  system: arquitectura-empresarial
